use_frameworks!

platform :ios, '9.0'

target 'WQAudioEdit_Example' do
  pod 'WQAudioEdit', :path => '../'

  target 'WQAudioEdit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
